<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Maitris-MacBook-Pro.local" name="com.baublebar.testcases.topmenubar.MyAccountOptionsTest" tests="5" failures="0" timestamp="29 May 2015 20:00:18 GMT" time="57.092" errors="1">
  <testcase name="LoginTest" time="11.879" classname="com.baublebar.testcases.topmenubar.MyAccountOptionsTest"/>
  <testcase name="LoginTest" time="6.307" classname="com.baublebar.testcases.topmenubar.MyAccountOptionsTest">
    <error type="java.lang.AssertionError" message="expected [INVITE FRIENDS] but found [TRANSFERS]">
      <![CDATA[java.lang.AssertionError: expected [INVITE FRIENDS] but found [TRANSFERS]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.baublebar.pages.TopMenuBarPage.myAccountOptions(TopMenuBarPage.java:349)
	at com.baublebar.testcases.topmenubar.MyAccountOptionsTest.LoginTest(MyAccountOptionsTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </error>
  </testcase> <!-- LoginTest -->
  <testcase name="LoginTest" time="10.173" classname="com.baublebar.testcases.topmenubar.MyAccountOptionsTest"/>
  <testcase name="LoginTest" time="16.637" classname="com.baublebar.testcases.topmenubar.MyAccountOptionsTest"/>
  <testcase name="LoginTest" time="12.096" classname="com.baublebar.testcases.topmenubar.MyAccountOptionsTest"/>
</testsuite> <!-- com.baublebar.testcases.topmenubar.MyAccountOptionsTest -->
